name: AvoidTPA
main: com.bnana.AvoidTPA
version: 1.0
api-version: "1.19"

commands:
  tpa:
    description: Send a teleport request to a player.
  tpahere:
    description: Request a player to teleport to you.
  tpaccept:
    description: Accept the pending teleport request.
  tpdeny:
    description: Deny the pending teleport request.
  tpaguitoggle:
    description: Toggle the TPA GUI on/off for yourself.
